displayName: Finance Statement Analysis Agent
schemaName: cree1_FinanceStatementAnalysisAgent
accessControlPolicy: GroupMembership
authenticationMode: Integrated
authenticationTrigger: Always
configuration:
  channels:
    - channelId: MsTeams

    - channelId: Microsoft365Copilot

  settings:
    GenerativeActionsEnabled: true

  isAgentConnectable: true
  publishOnImport: true
  gPTSettings:
    defaultSchemaName: cree1_FinanceStatementAnalysisAgent.gpt.default

  isLightweightBot: false
  aISettings:
    useModelKnowledge: true
    isFileAnalysisEnabled: true
    isSemanticSearchEnabled: true
    optInUseLatestModels: false

  recognizer:
    kind: GenerativeAIRecognizer

publishedOn: 2026-03-25T11:46:10.0000000Z
template: default-2.1.0
language: 1033