// This file is automatically generated by Microsoft 365 Agents Toolkit.
// The teamsfx tasks defined in this file require Microsoft 365 Agents Toolkit version >= 5.0.0.
// See https://aka.ms/teamsfx-tasks for details on how to customize each task.
{
    "version": "2.0.0",
    "tasks": [
        {
            "label": "Start Agent Locally",
            "dependsOn": [
                "Validate prerequisites",
                "Create resources"
            ],
            "dependsOrder": "sequence"
        },
        {
            "label": "Validate prerequisites",
            "type": "teamsfx",
            "command": "debug-check-prerequisites",
            "args": {
                "prerequisites": [
                    "m365Account"
                ]
            }
        },
        {
            "label": "Create resources",
            "type": "teamsfx",
            "command": "provision",
            "args": {
                "env": "local"
            }
        }
        {
            "label": "Install dependencies",
            "type": "shell",
            "command": "npm install",
            "presentation": {
                "reveal": "silent",
                "panel": "new"
            },
            "runOptions": { "runOn": "folderOpen" }
        }
    ]
}