openapi: 3.0.0
info:
  title: Repair Service
  description: A simple service to manage repairs
  version: 1.0.0

servers:
  - url: ${{OPENAPI_SERVER_URL}}/api
    description: The repair api server

components:
  securitySchemes:
    apiKey:
      type: apiKey
      in: header
      name: X-API-Key

  schemas:
    Repair:
      type: object
      properties:
        id:
          type: string
          description: The unique identifier of the repair
        title:
          type: string
          description: The short summary of the repair
        description:
          type: string
          description: The detailed description of the repair
        assignedTo:
          type: string
          description: The user who is responsible for the repair
        date:
          type: string
          format: date-time
          description: The date of the repair
        image:
          type: string
          format: uri
          description: The image URL of the repair

paths:
  /repairs:
    get:
      operationId: listRepairs
      summary: List all repairs
      parameters:
        - name: assignedTo
          in: query
          required: false
          schema:
            type: string
      security:
        - apiKey: []
      responses:
        '200':
          description: A list of repairs
          content:
            application/json:
              schema:
                type: object
                properties:
                  results:
                    type: array
                    items:
                      $ref: '#/components/schemas/Repair'

  /repairs/{id}:
    patch:
      operationId: updateRepair
      summary: Update an existing repair record
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      security:
        - apiKey: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                assignedTo:
                  type: string
      responses:
        '200':
          description: The updated repair record
          content:
            application/json:
              schema:
                type: object
                properties:
                  updatedRepair:
                    $ref: '#/components/schemas/Repair'
