displayName: KK Policy Agent(Topic)
schemaName: cred8_agent_Ai98b3
accessControlPolicy: ChatbotReaders
authenticationMode: Integrated
authenticationTrigger: Always
configuration:
  channels:
    - channelId: MsTeams

  settings:
    GenerativeActionsEnabled: true

  isAgentConnectable: true
  gPTSettings:
    defaultSchemaName: cred8_agent_Ai98b3.gpt.default

  isLightweightBot: false
  aISettings:
    useModelKnowledge: true
    isFileAnalysisEnabled: true
    isSemanticSearchEnabled: true
    optInUseLatestModels: false

  recognizer:
    kind: GenerativeAIRecognizer

publishedOn: 2025-10-07T06:09:13.0000000Z
template: default-2.1.0
language: 1033