displayName: KK Enterprises Policy Agent
schemaName: cred8_kkEnterprisesPolicyAgent
accessControlPolicy: ChatbotReaders
authenticationMode: Integrated
authenticationTrigger: Always
configuration:
  channels:
    - channelId: MsTeams

  gPTSettings:
    defaultSchemaName: cred8_kkEnterprisesPolicyAgent.gpt.default

  isLightweightBot: false
  aISettings: {}

publishedOn: 2025-10-09T14:00:28.0000000Z
template: gpt-1.1.0
language: 1033