openapi: 3.0.0
info:
  title: AI Volunteering Search API
  description: An API for searching volunteer opportunities using vector queries.
  version: 1.0.0
servers:
  - url: https://aivolunteeringsearch.search.windows.net
    description: Azure AI Volunteering Search Service
paths:
  /indexes/vol/docs/search:
    post:
      summary: Search volunteer opportunities
      description: Retrieves volunteer opportunities using vector-based queries.
      operationId: searchVolunteerOpportunities
      tags:
        - Volunteer Opportunities
      parameters:
        - name: api-version
          in: query
          required: true
          schema:
            type: string
            default: 2025-03-01-preview
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                count:
                  type: boolean
                  example: true
                vectorQueries:
                  type: array
                  items:
                    type: object
                    properties:
                      kind:
                        type: string
                        example: text
                      text:
                        type: string
                        example: Azure API Management
                      fields:
                        type: string
                        example: body_vector
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  value:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                        title:
                          type: string
                        description:
                          type: string
                        location:
                          type: string
                        date:
                          type: string
                          format: date-time
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
security:
  - ApiKeyAuth: []
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: api-key
